# Generated by Django 5.0.7 on 2024-11-04 14:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLuminarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('tipo_lampara', models.CharField(max_length=50, verbose_name='Tipo de lampara')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('potencia', models.FloatField(max_length=500, verbose_name='Potencia (W)')),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de instalación')),
                ('cod_certificacion', models.CharField(max_length=100, verbose_name='Código de certificación')),
                ('fecha_certificacion', models.DateField(verbose_name='Fecha de certificación')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Detalle luminaria',
                'verbose_name_plural': 'Detalle luminarias',
                'db_table': 'detalle_luminarias',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=15, verbose_name='Run')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('a_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('a_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('direccon', models.CharField(max_length=500, verbose_name='Dirección')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Representante legal',
                'verbose_name_plural': 'Respresentantes legales',
                'db_table': 'representante_legal',
            },
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=15, verbose_name='Run')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('a_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('a_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('direccon', models.CharField(max_length=500, verbose_name='Dirección')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
                'db_table': 'titular',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('longitud', models.FloatField(max_length=500, verbose_name='Longitud')),
                ('latitud', models.FloatField(max_length=500, verbose_name='Latitud')),
                ('tipo_alumbrado', models.CharField(choices=[('v', 'Vehicular'), ('p', 'Peatonal'), ('i', 'Industrial'), ('o', 'Ornamental')], default='v', max_length=1, verbose_name='Tipo de alumbrado')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('nv_cumplimiento', models.CharField(choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1, verbose_name='Nivel de cumplimiento')),
                ('estado', models.IntegerField(default=0)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('detalle_luminarias', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.detalleluminarias')),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.representantelegal')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.titular')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
            },
        ),
    ]
