# Generated by Django 5.1.4 on 2024-12-08 13:54

import django.db.models.deletion
import django.utils.timezone
import services.utils.GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleLuminaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('tipo_lampara', models.CharField(max_length=50, verbose_name='Tipo de lampara')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('potencia', models.FloatField(max_length=500, verbose_name='Potencia (W)')),
                ('fecha_instalacion', models.DateField(verbose_name='Fecha de instalación')),
                ('cod_certificacion', models.CharField(max_length=100, verbose_name='Código de certificación')),
                ('fecha_certificacion', models.DateField(verbose_name='Fecha de certificación')),
            ],
            options={
                'verbose_name': 'Detalle luminaria',
                'verbose_name_plural': 'Detalle luminarias',
                'db_table': 'detalleLuminaria',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=15, verbose_name='Run')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('a_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('a_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.persona')),
            ],
            options={
                'verbose_name': 'Representante legal',
                'verbose_name_plural': 'Respresentantes legales',
                'db_table': 'representanteLegal',
            },
            bases=('proyectos.persona',),
        ),
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proyectos.persona')),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
                'db_table': 'titular',
            },
            bases=('proyectos.persona',),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('latitud', models.FloatField(max_length=500, verbose_name='Latitud')),
                ('longitud', models.FloatField(max_length=500, verbose_name='Longitud')),
                ('tipo_alumbrado', models.CharField(choices=[('v', 'Vehicular'), ('p', 'Peatonal'), ('i', 'Industrial'), ('o', 'Ornamental')], default='v', max_length=1, verbose_name='Tipo de alumbrado')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('foto', models.ImageField(default='proyectos/proyecto.png', null=True, upload_to=services.utils.GenerarNombre.GenerarNombre.generar_nombre_proyecto)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('detalle_luminarias', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.detalleluminaria')),
                ('representante_legal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.representantelegal')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.titular')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
            },
        ),
    ]
