# Generated by Django 5.0.7 on 2024-11-26 18:14

import services.utils.GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(default='proyectos/proyecto.png', null=True, upload_to=services.utils.GenerarNombre.GenerarNombre.generar_nombre_proyecto),
        ),
    ]
