# Generated by Django 5.0.7 on 2024-11-19 17:50

import proyectos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(default='proyectos/proyecto.png', null=True, upload_to=proyectos.models.Proyecto.generarNombre),
        ),
    ]
