# Generated by Django 5.0.7 on 2024-11-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.IntegerField(default='0'),
        ),
    ]
