# Generated by Django 5.1.2 on 2024-11-23 20:31

import services.utils.GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyecto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(default='proyectos/proyecto.png', null=True, upload_to=services.utils.GenerarNombre.GenerarNombre.generar_nombre_proyecto),
        ),
    ]
