# Generated by Django 5.0.7 on 2024-11-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='estado',
        ),
    ]
