# Generated by Django 5.0.7 on 2024-10-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='cumpl',
            field=models.IntegerField(default=0, verbose_name='Nivel Cumplimiento'),
        ),
    ]
