# Generated by Django 5.1.2 on 2024-11-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(default='Suerte.200%', max_length=128, verbose_name='Clave'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Correo'),
        ),
    ]
