# Generated by Django 5.0.7 on 2024-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='humedad',
            field=models.FloatField(default=9, verbose_name='Humedad (%)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='temperatura',
            field=models.FloatField(default=8, verbose_name='Temperatura (°C)'),
            preserve_default=False,
        ),
    ]
