# Generated by Django 5.0.7 on 2024-11-25 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacion', '0002_alter_fiscalizacion_foto'),
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='fiscalizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalizacion.fiscalizacion'),
        ),
    ]
