# Generated by Django 5.0.7 on 2024-11-19 17:22

import django.db.models.deletion
from services.utils.GenerarNombre import GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacion', '0001_initial'),
        ('mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='foto',
            field=models.ImageField(default='medicion/medicion.png', null=True, upload_to=GenerarNombre.generar_nombre),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='fiscalizacion',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='fiscalizacion.fiscalizacion'),
        ),
        migrations.AlterField(
            model_name='medicion',
            name='tipo',
            field=models.CharField(choices=[('0', 'Iluminancia'), ('1', 'Luminancia')], max_length=1, verbose_name='Tipo'),
        ),
    ]
