# Generated by Django 5.1.2 on 2024-11-23 20:31

import services.utils.GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0002_medicion_foto_alter_medicion_fiscalizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='foto',
            field=models.ImageField(default='medicion/medicion.png', null=True, upload_to=services.utils.GenerarNombre.GenerarNombre.generar_nombre_medicion),
        ),
    ]
