# Generated by Django 5.1.2 on 2024-11-25 23:30

import django.db.models.deletion
import django.utils.timezone
import services.utils.GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiscalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='medicion/medicion.png', null=True, upload_to=services.utils.GenerarNombre.GenerarNombre.generar_nombre_medicion)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proyectos.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Fiscalización',
                'verbose_name_plural': 'Fiscalizaciones',
                'db_table': 'fiscalizacion',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fiscalizacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fiscalizacion.fiscalizacion')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reporte',
            },
        ),
    ]
