# Generated by Django 5.0.7 on 2024-11-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalizacion',
            name='humedad',
        ),
        migrations.RemoveField(
            model_name='fiscalizacion',
            name='temperatura',
        ),
        migrations.AlterField(
            model_name='fiscalizacion',
            name='nivel_cumplimeinto',
            field=models.FloatField(blank=True, null=True, verbose_name='Cumplimiento (%)'),
        ),
    ]
