# Generated by Django 5.0.7 on 2024-11-25 19:15

import services.utils.GenerarNombre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalizacion',
            name='foto',
            field=models.ImageField(default='fiscalizacion/fiscalizacion.png', null=True, upload_to=services.utils.GenerarNombre.GenerarNombre.generar_nombre_fiscalizacion),
        ),
    ]
