# Generated by Django 5.0.7 on 2024-10-23 03:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='TipoAlumbradoArt5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_cumplimiento', models.CharField(blank=True, choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1, null=True)),
                ('tipo', models.CharField(choices=[('art5', 'Peatonal, Vehicular e Industrial'), ('art6', 'Ornamental y Decorativo'), ('art7', 'Deportivo y Recreacional'), ('art8', 'Publicitario'), ('art9', 'Cañones de Luz o Proyectores Láser')], default='art5', max_length=4)),
                ('estado', models.IntegerField(default='0')),
                ('direccion', models.CharField(max_length=250, verbose_name='Ubicación')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('menor_igual_90grados', models.FloatField(verbose_name='Intensidad Luminosa <= 90º')),
                ('mayor_90grados', models.FloatField(verbose_name='Intensidad Luminosa > 90º')),
                ('clase_luminaria', models.CharField(max_length=50, verbose_name='Clase de luminaria')),
                ('emision_reflexion', models.FloatField(verbose_name='Emisión por Reflexión')),
                ('proteccion_especial', models.CharField(max_length=2, verbose_name='Área de protección especial')),
                ('radiancia_espectral', models.FloatField(verbose_name='Radiancia Espectral')),
                ('emision_conjunta', models.CharField(max_length=2, verbose_name='Emision conjunta considerada')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Medicion art5',
                'verbose_name_plural': 'Mediciones art5',
            },
        ),
        migrations.CreateModel(
            name='TipoAlumbradoArt6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_cumplimiento', models.CharField(blank=True, choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1, null=True)),
                ('tipo', models.CharField(choices=[('art5', 'Peatonal, Vehicular e Industrial'), ('art6', 'Ornamental y Decorativo'), ('art7', 'Deportivo y Recreacional'), ('art8', 'Publicitario'), ('art9', 'Cañones de Luz o Proyectores Láser')], default='art5', max_length=4)),
                ('estado', models.IntegerField(default='0')),
                ('direccion', models.CharField(max_length=250, verbose_name='Ubicación')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tipo_flujo_luminoso', models.CharField(choices=[('i', 'indivudial'), ('l', 'lineal'), ('m', 'malla')], default='', max_length=1, verbose_name='Tipo de flujo luminoso')),
                ('valor_flujo_luminoso', models.FloatField(verbose_name='Flujo luminoso de luminaria')),
                ('Hemisferio_superior', models.FloatField(verbose_name='Emisión al hemisferio superior')),
                ('proteccion_especial', models.CharField(max_length=2, verbose_name='Área de protección especial')),
                ('reflexion_luminancia', models.FloatField(verbose_name='Emisión por Reflexión: Luminancia')),
                ('temperatura_luz_blanca', models.FloatField(verbose_name='Temperatura de color: Luz Blanca')),
                ('temperatura_luz_color', models.FloatField(verbose_name='Temperatura de color: Luces multicolor')),
                ('limite_horario', models.CharField(max_length=2, verbose_name='Limite horario')),
                ('horario_extendido', models.CharField(max_length=2, verbose_name='Permiso de extención horaria')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Medicion art6',
                'verbose_name_plural': 'Mediciones art6',
            },
        ),
        migrations.CreateModel(
            name='CatalogoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicion_art5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.tipoalumbradoart5')),
                ('medicion_art6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.tipoalumbradoart6')),
            ],
            options={
                'verbose_name': 'Catálogo de Mediciones',
                'verbose_name_plural': 'Catálogo de Mediciones',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
        migrations.AddField(
            model_name='tipoalumbradoart6',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_mediciones.usuario'),
        ),
        migrations.AddField(
            model_name='tipoalumbradoart5',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_mediciones.usuario'),
        ),
    ]
