# Generated by Django 5.0.7 on 2024-10-18 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_alumbrado_art5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=250, verbose_name='Ubicación')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('menor_igual_90grados', models.FloatField(verbose_name='Intensidad Luminosa <= 90º')),
                ('mayor_90grados', models.FloatField(verbose_name='Intensidad Luminosa > 90º')),
                ('clase_luminaria', models.CharField(max_length=50, verbose_name='Clase de luminaria')),
                ('emision_reflexion', models.FloatField(verbose_name='Emisión por Reflexión')),
                ('proteccion_especial', models.CharField(max_length=2, verbose_name='Área de protección especial')),
                ('radiancia_espectral', models.FloatField(verbose_name='Radiancia Espectral')),
                ('emision_conjunta', models.CharField(max_length=2, verbose_name='Emision conjunta considerada')),
                ('Observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Medicion_art5',
                'verbose_name_plural': 'Mediciones_art5',
            },
        ),
    ]
