# Generated by Django 5.0.7 on 2024-10-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoalumbradoart6',
            name='tipo',
            field=models.CharField(choices=[('art5', 'Peatonal, Vehicular e Industrial'), ('art6', 'Ornamental y Decorativo'), ('art7', 'Deportivo y Recreacional'), ('art8', 'Publicitario'), ('art9', 'Cañones de Luz o Proyectores Láser')], default='art6', max_length=4),
        ),
    ]
