# Generated by Django 5.0.7 on 2024-10-19 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=1000, verbose_name='Descripcion')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'rol',
            },
        ),
        migrations.RenameField(
            model_name='tipo_alumbrado_art5',
            old_name='Observaciones',
            new_name='observaciones',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10, verbose_name='RUN')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['nombre', 'paterno', 'materno'],
            },
        ),
    ]
