# Generated by Django 5.0.7 on 2024-10-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0002_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_alumbrado_art5',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.usuario'),
        ),
    ]
