# Generated by Django 5.0.7 on 2024-10-26 06:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0002_alter_tipoalumbradoart6_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoalumbradoart5',
            options={'verbose_name': 'Medición Art. 5', 'verbose_name_plural': 'Mediciones Art. 5'},
        ),
        migrations.AlterModelOptions(
            name='tipoalumbradoart6',
            options={'verbose_name': 'Medición Art. 6', 'verbose_name_plural': 'Mediciones Art. 6'},
        ),
        migrations.RenameField(
            model_name='tipoalumbradoart6',
            old_name='Hemisferio_superior',
            new_name='hemisferio_superior',
        ),
        migrations.AddField(
            model_name='catalogomedicion',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tipoalumbradoart6',
            name='horario_extendido',
            field=models.CharField(max_length=2, verbose_name='Permiso de extensión horaria'),
        ),
        migrations.AlterField(
            model_name='tipoalumbradoart6',
            name='limite_horario',
            field=models.CharField(max_length=2, verbose_name='Límite horario'),
        ),
    ]
