# Generated by Django 5.0.7 on 2024-10-30 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0004_alter_tipoalumbradoart5_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=15, verbose_name='Run')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('a_paterno', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('a_materno', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('direccon', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Titular',
                'verbose_name_plural': 'Titulares',
                'db_table': 'titular',
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='tipoalumbradoart5',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tipoalumbradoart6',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CatalogoMedicion',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='TipoAlumbradoArt5',
        ),
        migrations.DeleteModel(
            name='TipoAlumbradoArt6',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
