# Generated by Django 5.0.7 on 2024-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0005_alter_tipo_alumbrado_art5_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_alumbrado_art5',
            name='tipo',
            field=models.CharField(choices=[('art5', 'Peatonal, Vehicular e Industrial'), ('art6', 'Ornamental y Decorativo'), ('art7', 'Deportivo y Recreacional'), ('art8', 'Publicitario'), ('art9', 'Cañones de Luz o Proyectores Láser')], default='art5', max_length=4),
        ),
    ]
