# Generated by Django 5.0.7 on 2024-10-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0006_alter_tipo_alumbrado_art5_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_alumbrado_art5',
            name='nivel_cumplimiento',
            field=models.CharField(choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1),
        ),
    ]
