# Generated by Django 5.0.7 on 2024-10-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0006_detalleluminarias_representantelegar_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RepresentanteLegar',
            new_name='RepresentanteLegal',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='nv_cumplimiento',
            field=models.CharField(choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1, verbose_name='Nivel de cumplimiento'),
        ),
        migrations.AlterField(
            model_name='detalleluminarias',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
    ]
