# Generated by Django 5.0.7 on 2024-10-22 00:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0007_tipo_alumbrado_art5_nivel_cumplimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_alumbrado_art6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_cumplimiento', models.CharField(choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1)),
                ('tipo_alumbrado', models.CharField(choices=[('art5', 'Peatonal, Vehicular e Industrial'), ('art6', 'Ornamental y Decorativo'), ('art7', 'Deportivo y Recreacional'), ('art8', 'Publicitario'), ('art9', 'Cañones de Luz o Proyectores Láser')], default='art6', max_length=4)),
                ('direccion', models.CharField(max_length=250, verbose_name='Ubicación')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('tipo_flujo_luminoso', models.CharField(choices=[('i', 'indivudial'), ('l', 'lineal'), ('m', 'malla')], default='', max_length=1, verbose_name='Tipo de flujo luminoso')),
                ('valor_flujo_luminoso', models.FloatField(verbose_name='Flujo luminoso de luminaria')),
                ('Hemisferio_superior', models.FloatField(verbose_name='Emision al hemisferio superior')),
                ('proteccion_especial', models.CharField(max_length=2, verbose_name='Área de protección especial')),
                ('reflexion_luminancia', models.FloatField(verbose_name='Emisiòn por Reflexiòn: Luminancia')),
                ('temperatura_luz_blanca', models.FloatField(verbose_name='Temperatura de color: Luz Blanca')),
                ('temperatura_luz_color', models.FloatField(verbose_name='Temperatura de color: Luces multicolor')),
                ('limite_horario', models.CharField(max_length=2, verbose_name='Limite horario')),
                ('horario_extendido', models.CharField(max_length=2, verbose_name='Permiso de extención horaria')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.usuario')),
            ],
            options={
                'verbose_name': 'Medicion_art6',
                'verbose_name_plural': 'Mediciones art6',
            },
        ),
    ]
