# Generated by Django 5.0.7 on 2024-11-02 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0007_rename_representantelegar_representantelegal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='detalle_luminarias',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='representante_legal',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='titular',
        ),
        migrations.DeleteModel(
            name='DetalleLuminarias',
        ),
        migrations.DeleteModel(
            name='RepresentanteLegal',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
        migrations.DeleteModel(
            name='Titular',
        ),
    ]
