# Generated by Django 5.0.7 on 2024-11-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0009_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallemedicion',
            old_name='instumento_medicion',
            new_name='instrumento_medicion',
        ),
        migrations.RenameField(
            model_name='medicion',
            old_name='DetalleMedicion',
            new_name='detalleMedicion',
        ),
        migrations.AlterField(
            model_name='medicion',
            name='cumplimiento',
            field=models.CharField(blank=True, choices=[('0', 'No'), ('1', 'Si')], max_length=1, null=True, verbose_name='Cumplimiento'),
        ),
    ]
