# Generated by Django 5.0.7 on 2024-10-22 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0009_rename_tipo_tipo_alumbrado_art5_tipo_alumbrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_alumbrado_art5',
            name='nivel_cumplimiento',
        ),
        migrations.RemoveField(
            model_name='tipo_alumbrado_art6',
            name='nivel_cumplimiento',
        ),
        migrations.CreateModel(
            name='CatalogoMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_cumplimiento', models.CharField(choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1)),
                ('medicion_art5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.tipo_alumbrado_art5')),
                ('medicion_art6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.tipo_alumbrado_art6')),
            ],
            options={
                'verbose_name': 'Medicion',
                'verbose_name_plural': 'Mediciones',
            },
        ),
    ]
