# Generated by Django 5.0.7 on 2024-11-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0010_rename_instumento_medicion_detallemedicion_instrumento_medicion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='detalleMedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.detallemedicion'),
        ),
    ]
