# Generated by Django 5.0.7 on 2024-10-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0010_remove_tipo_alumbrado_art5_nivel_cumplimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomedicion',
            name='medicion_art5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.tipo_alumbrado_art5'),
        ),
        migrations.AlterField(
            model_name='catalogomedicion',
            name='medicion_art6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo_mediciones.tipo_alumbrado_art6'),
        ),
    ]
