# Generated by Django 5.0.7 on 2024-10-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0011_alter_catalogomedicion_medicion_art5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomedicion',
            name='medicion_art5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_mediciones.tipo_alumbrado_art5'),
        ),
        migrations.AlterField(
            model_name='catalogomedicion',
            name='medicion_art6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo_mediciones.tipo_alumbrado_art6'),
        ),
    ]
