# Generated by Django 5.0.7 on 2024-11-02 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0011_alter_medicion_detallemedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
