# Generated by Django 5.0.7 on 2024-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0012_alter_catalogomedicion_medicion_art5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogomedicion',
            name='nivel_cumplimiento',
            field=models.CharField(blank=True, choices=[('0', 'Sin evaluación'), ('1', 'Critico'), ('2', 'Bajo'), ('3', 'Medio'), ('4', 'Alto')], default='0', max_length=1, null=True),
        ),
    ]
