# Generated by Django 5.0.7 on 2024-10-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0013_alter_catalogomedicion_nivel_cumplimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_alumbrado_art5',
            name='estado_evaluacion',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='tipo_alumbrado_art6',
            name='estado_evaluacion',
            field=models.IntegerField(default='0'),
        ),
    ]
