# Generated by Django 5.0.7 on 2024-10-22 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0014_tipo_alumbrado_art5_estado_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogomedicion',
            options={'verbose_name': 'Catálogo de Mediciones', 'verbose_name_plural': 'Catálogo de Mediciones'},
        ),
    ]
