# Generated by Django 5.0.7 on 2024-10-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_mediciones', '0015_alter_catalogomedicion_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_alumbrado_art5',
            old_name='estado_evaluacion',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='tipo_alumbrado_art6',
            old_name='estado_evaluacion',
            new_name='estado',
        ),
    ]
